import { Injectable } from '@angular/core';
import { clothes } from 'src/app/shared/models/clothes';

@Injectable({
  providedIn: 'root'
})
export class ClothesService {

  constructor() { }

  getAll():clothes[]{
    return[
      {
        id:1,
        name: 'Falda negra de lineas',
        price: 60000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa1.jpg',
        tags: ['falda de prenses, falda negra, falda de linea'],
      },
      {
        id:2,
        name: 'Falda colores de lineas',
        price: 60000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa2.jpg',
        tags: ['falda de prenses,falda de linea'],
      },
      {
        id:3,
        name: 'Falda de cuadros',
        price: 85000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa3.jpg',
        tags: ['falda de prenses,falda de linea'],
      },
      {
        id:4,
        name: 'Top negro con morado',
        price: 42000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa4.jpg',
        tags: ['falda de prenses,falda de linea'],
      },
      {
        id:5,
        name: 'Buso anime',
        price: 90000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa5.jpg',
        tags: ['falda de prenses,falda de linea'],
      },
      {
        id:6,
        name: 'Camiseta anime',
        price: 65000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa6.jpg',
        tags: ['falda de prenses,falda de linea'],
      },
      {
        id:7,
        name: 'Falda de prenses',
        price: 55000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa7.jpg',
        tags: ['falda de prenses,falda de linea'],
      },
      {
        id:8,
        name: 'Blusa anime',
        price: 65000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa8.jpg',
        tags: ['falda de prenses,falda de linea'],
      },
      {
        id:9,
        name: 'Faldas de lineas blanca',
        price: 60000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa9.jpg',
        tags: ['falda de prenses,falda de linea'],
      },
      {
        id:10,
        name: 'Buso de cuadros con cadenas',
        price: 85000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa10.jpg',
        tags: ['falda de prenses,falda de linea'],
      },
      {
        id:11,
        name: 'Falda de cuadros verde con negro',
        price: 70000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa11.jpg',
        tags: ['falda de prenses,falda de linea'],
      },
      {
        id:12,
        name: 'Pantalon de cuadros verde',
        price: 110000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa12.jpg',
        tags: ['falda de prenses,falda de linea'],
      },
      {
        id:13,
        name: 'Falda de cuadros roja con negro',
        price: 70000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa13.jpg',
        tags: ['falda de prenses,falda de linea'],
      },
      {
        id:14,
        name: 'Blusa sakura',
        price: 60000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa14.jpg',
        tags: ['falda de prenses,falda de linea'],
      },
      {
        id:15,
        name: 'Pantalon de cuadros rojo',
        price: 110000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa15.jpg',
        tags: ['falda de prenses,falda de linea'],
      },
      {
        id:16,
        name: 'Blusa matrix',
        price: 60000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa16.jpg',
        tags: ['falda de prenses,falda de linea'],
      },
      {
        id:17,
        name: 'Top con correas',
        price: 60000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa17.jpg',
        tags: ['falda de prenses,falda de linea'],
      },
      {
        id:18,
        name: 'Cadenas',
        price: 13000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa18.jpg',
        tags: ['falda de prenses,falda de linea'],
      },
      {
        id:19,
        name: 'Chocker corazon',
        price: 14000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa19.jpg',
        tags: ['falda de prenses,falda de linea'],
      },
      {
        id:20,
        name: 'Medias fuego',
        price: 14000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa20.jpg',
        tags: ['falda de prenses,falda de linea'],
      },
      {
        id:21,
        name: 'Medias de cuadros',
        price: 12000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa21.jpg',
        tags: ['falda de prenses,falda de linea'],
      },
      {
        id:22,
        name: 'Medias bucaneras con linea',
        price: 16000,
        favorite: false, 
        origins: ['Made in Colombia'],
        stars: 4.5,
        imageUrl: '/assets/images/ropa22.jpg',
        tags: ['falda de prenses,falda de linea'],
      }
    ]
  }
}
